[project]
name = "ricoshacl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyshacl>=0.30.1",
    "pytest>=9.0.2",
    "rdflib>=7.5.0",
]

[tool.pytest]
testpaths = [ "tests/" ]
